# -*- coding: utf-8 -*-
"""GenderInequalityIndex

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_fLG_LMmKe99J4wonEt9si9p0ENGj8d
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

genderIndex_df = pd.read_csv('FAO_AS_4537.csv')

genderIndex_df = genderIndex_df.dropna(subset=['TIME_PERIOD', 'OBS_VALUE'])

genderIndex_df['TIME_PERIOD'] = genderIndex_df['TIME_PERIOD'].astype(int)

X = genderIndex_df[['TIME_PERIOD']]
y = genderIndex_df['OBS_VALUE']

model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)

year_2026 = pd.DataFrame({'TIME_PERIOD': [2026]})
forecast_2026 = model.predict(year_2026)[0]
print(f"🔮 Forecasted Gender Inequality (OBS_VALUE) for 2026: {forecast_2026:.2f}")

plt.figure(figsize=(10, 6))
plt.scatter(X, y, label='Actual', color='blue')
plt.plot(X, y_pred, label='Fitted Line', color='red')
plt.scatter(2026, forecast_2026, color='green', label='Forecast 2026', zorder=5)
plt.xlabel('Time Period (Year)')
plt.ylabel('Inequality Income (OBS_VALUE)')
plt.title('Linear Regression: Inequality Income vs Time')
plt.legend()
plt.grid(True)
plt.show()

residuals = y - y_pred
plt.figure(figsize=(10, 6))
plt.scatter(X, residuals, color='purple')
plt.axhline(0, color='black', linestyle='--')
plt.title('Residuals Plot')
plt.xlabel('Time Period (Year)')
plt.ylabel('Residuals')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(residuals, kde=True, color='teal')
plt.title('Distribution of Residuals')
plt.xlabel('Residuals')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

print(f"Model Coefficients:\nSlope: {model.coef_[0]}, Intercept: {model.intercept_}")

future_years = pd.DataFrame({'TIME_PERIOD': [2025, 2026, 2027, 2028]})
future_predictions = model.predict(future_years)

forecast_df = future_years.copy()
forecast_df['Forecast_OBS_VALUE'] = future_predictions

print("\n📊 Forecasts for Gender Inequality (OBS_VALUE):\n")
print(forecast_df.to_string(index=False))

plt.figure(figsize=(10, 6))
# Historical
plt.scatter(X, y, label='Actual', color='blue')
plt.plot(X, y_pred, label='Fitted Line', color='red')
# Forecast
plt.scatter(forecast_df['TIME_PERIOD'], forecast_df['Forecast_OBS_VALUE'], color='green', label='Forecast (2025–2028)', zorder=5)
for i, txt in enumerate(forecast_df['Forecast_OBS_VALUE']):
    plt.annotate(f"{txt:.2f}", (forecast_df['TIME_PERIOD'][i], forecast_df['Forecast_OBS_VALUE'][i]),
                 textcoords="offset points", xytext=(0,10), ha='center', fontsize=9)

plt.xlabel('Time Period (Year)')
plt.ylabel('Inequality Income (OBS_VALUE)')
plt.title('Gender Inequality Forecast: 2025–2028')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()