# -*- coding: utf-8 -*-
"""VoxAequalisChange.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0bEYhZDcz758_AbpnksF9JF4Sky0cy5
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

df = pd.read_csv("Inequality in Income.csv")

df.columns = [col.strip().replace('Inequality in income (', '').replace(')', '') for col in df.columns]

year_columns = [col for col in df.columns if col.isdigit()]
df_years = df[year_columns]

df_long = df_years.melt(var_name='Year', value_name='Inequality_Income')
df_long['Year'] = df_long['Year'].astype(int)

X = df_long[['Year']]
y = df_long['Inequality_Income']

model = LinearRegression()
model.fit(X, y)

future_years = pd.DataFrame({'Year': list(range(2026, 2031))})
future_years['LR_Prediction'] = model.predict(future_years[['Year']])
future_years['Yearly_Change'] = future_years['LR_Prediction'].diff()

combined_years = list(df_long['Year']) + list(future_years['Year'])
combined_values = list(df_long['Inequality_Income']) + list(future_years['LR_Prediction'])

plt.figure(figsize=(10, 6))
plt.plot(df_long['Year'], df_long['Inequality_Income'], label='Historical', marker='o', color='blue')
plt.plot(future_years['Year'], future_years['LR_Prediction'], label='Forecast (Linear Regression)', linestyle='--', marker='x', color='green')
plt.title('Historical vs Forecasted Income Inequality')
plt.xlabel('Year')
plt.ylabel('Inequality (%)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(future_years['Year'], future_years['LR_Prediction'], color='seagreen', edgecolor='black')
plt.title('Forecasted Income Inequality (2026–2030)')
plt.xlabel('Year')
plt.ylabel('Predicted Inequality (%)')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(future_years['Year'], future_years['Yearly_Change'],
        color=['grey' if x == 0 else 'green' if x < 0 else 'red' for x in future_years['Yearly_Change']],
        edgecolor='black')
plt.axhline(0, color='black', linewidth=0.8, linestyle='dashed')
plt.title('Yearly Change in Predicted Inequality')
plt.xlabel('Year')
plt.ylabel('Δ Inequality (%)')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

print(future_years[['Year', 'LR_Prediction', 'Yearly_Change']])