# -*- coding: utf-8 -*-
"""VoxAequalisGenderWage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mfWZgXCIIZngwFnw7xpNrISuQ8f69GHP
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import seaborn as sns

gendergap_df = pd.read_csv('gendergapinaverage new.csv')

gendergap_clean = gendergap_df[['Year', 'Gender wage gap %']].dropna()
gendergap_clean = gendergap_clean[gendergap_clean['Gender wage gap %'] > 0]

X_gender = gendergap_clean[['Year']]
y_gender = gendergap_clean['Gender wage gap %']

model_gender = LinearRegression()
model_gender.fit(X_gender, y_gender)

y_pred_gender = model_gender.predict(X_gender)
mse_gender = mean_squared_error(y_gender, y_pred_gender)
r2_gender = r2_score(y_gender, y_pred_gender)

print("Gender Wage Gap Model:")
print("MSE:", mse_gender)
print("R² Score:", r2_gender)

future_years = pd.DataFrame({'Year': range(2025, 2031)})
future_predictions = model_gender.predict(future_years)
print("\nPredicted Wage Gap (2025–2030):")
print(pd.DataFrame({'Year': future_years['Year'], 'Predicted Gap %': future_predictions.round(2)}))

plt.figure(figsize=(10, 5))
plt.plot(X_gender, y_gender, label="Actual")
plt.plot(X_gender, y_pred_gender, color='red', label="Predicted")
plt.scatter(future_years, future_predictions, color='green', label="Future Prediction")
plt.xlabel("Year")
plt.ylabel("Gender Wage Gap (%)")
plt.title("Gender Wage Gap Trend and Forecast")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.regplot(x='Year', y='Gender wage gap %', data=gendergap_clean, ci=95, scatter_kws={'alpha':0.6})
plt.title("Gender Wage Gap Trend with Confidence Interval")
plt.grid(True)
plt.tight_layout()
plt.show()

country_avg_gap = gendergap_df[['country', 'Gender wage gap %']].dropna().groupby('country').mean()
top_countries = country_avg_gap.sort_values('Gender wage gap %', ascending=False).head(10)

plt.figure(figsize=(10, 6))
sns.barplot(x=top_countries['Gender wage gap %'], y=top_countries.index, palette="magma")
plt.xlabel("Average Gender Wage Gap (%)")
plt.title("Top 10 Countries by Avg Gender Wage Gap")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.lineplot(data=gendergap_clean, x="Year", y="Gender wage gap %")
plt.title("Gender Wage Gap Over Time")
plt.grid(True)
plt.tight_layout()
plt.show()